#pragma once

#define DEFAULT_TEXTSIZE 20
#define DEFAULT_ASPEED 0.04f
#define DEFAULT_BSPEED 0.02f
#define DEFAULT_DONUTSIZE 2.0f
#define DEFAULT_DONUTDISTANCE 3.0f
#define DEFAULT_GOLCELLSIZE 2
#define DEFAULT_GOLSPEED 33
#define DEFAULT_EARTHSPEED 0.05f
#define DEFAULT_PONGSPEED 25.0f
#define DEFAULT_DVDSPEED 15.0f
#define DEFAULT_MAZEBUILDSPEED 10.0f
#define DEFAULT_MAZESOLVESPEED 10.0f
#define DEFAULT_PERLINSCALE 0.002f
#define DEFAULT_PERLINSPEED 2.0f
#define DEFAULT_MODEPRIMARY 11
#define DEFAULT_MODESECONDARY 1
#define DEFAULT_RANDOMMODE 0
#define DEFAULT_ANT_COUNT 2
#define DEFAULT_ANT_SPEED 200
#define DEFAULT_CURL_COUNT 5000
#define DEFAULT_RANDOM_POOL 0xFFFFFFF